# SPDX-FileCopyrightInfo: Copyright © DUNE Project contributors, see file LICENSE.md in module root
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception

Module: dune-common
Version: 2.10-git
Author: The Dune Core developers
Maintainer: dune-devel@lists.dune-project.org
Description: Basis infrastructure for all Dune modules
URL: https://gitlab.dune-project.org/core/dune-common
Python-Requires: pip>=21.a portalocker numpy wheel setuptools>=41 jinja2
Whitespace-Hook: Yes
