# .latexmkrc generated by CMake from UseLatexMk.cmake starts here

$bibtex = "@BIBTEX_COMPILER@ %O %S";
$dvips = "@DVIPS_CONVERTER@ %O -o %D %S";
$latex = "@LATEX_COMPILER@ %O %S";
$make = "@CMAKE_MAKE_COMMAND@";
$makeindex = "@MAKEINDEX_COMPILER@ %O -o %D %S";
$out_dir = "@CMAKE_CURRENT_BINARY_DIR@";
$pdf_mode = 1;
$pdflatex = "@PDFLATEX_COMPILER@ -shell-escape -interaction=nonstopmode %O %S";
$ps2pdf = "@PS2PDF_CONVERTER@ %O %S %D";

# .latexmkrc generated by CMake from UseLatexMk.cmake ends here
