// -*- tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*-
// vi: set et ts=4 sw=2 sts=2:
/** \file
 * \brief Contains <tt>#undef</tt>s for all preprocessor macros
 * defined by UG.
 *
 * This file is created automatically by the perl script <tt>undefAllMacros.pl</tt>.
 */

#undef DUNE_UGINCLUDES_HH
#undef __GM__
#undef two
#undef three
#undef __TWODIM__
#undef __THREEDIM__
#undef MODEL
#undef MODEL
#undef __GRAPE_TRUE__
#undef GRAPE_SUPPORT
#undef GRAPE_SUPPORT
#undef NETGEN_SUPPORT
#undef NETGEN_SUPPORT
#undef DEBUG_MODE
#undef DEBUG_MODE
#undef __XXL_MSIZE__
#undef __INTERPOLATION_MATRIX__
#undef __BLOCK_VECTOR_DESC__
#undef USE_FAMG
#undef __OVERLAP2__
#undef __PERIODIC_BOUNDARY__
#undef DIM_MAX
#undef DIM_OF_BND_MAX
#undef MAXLEVEL
#undef MAXOBJECTS
#undef MAXSELECTION
#undef MAX_SIDES_OF_ELEM
#undef MAX_EDGES_OF_ELEM
#undef MAX_CORNERS_OF_ELEM
#undef MAX_EDGES_OF_SIDE
#undef MAX_EDGES_OF_CORNER
#undef MAX_CORNERS_OF_SIDE
#undef MAX_CORNERS_OF_EDGE
#undef MAX_SIDES_OF_EDGE
#undef MAX_SONS
#undef MAX_SIDE_NODES
#undef MAX_SON_EDGES
#undef MAX_SIDES_TOUCHING
#undef MAX_ELEM_VECTORS
#undef MAX_NDOF_MOD_32
#undef MAX_NDOF
#undef DIM
#undef DIM_OF_BND
#undef DIM
#undef DIM_OF_BND
#undef MAXVOBJECTS
#undef MAXVECTORS
#undef NOVTYPE
#undef MAXDOMPARTS
#undef BITWISE_TYPE
#undef MAXMATRICES
#undef MAXCONNECTIONS
#undef MATRIXTYPE
#undef DIAGMATRIXTYPE
#undef FROM_VTNAME
#undef TO_VTNAME
#undef MAXVTNAMES
#undef NO_BLOCKVECTOR
#undef MAX_BV_NUMBER
#undef MAX_BV_LEVEL
#undef BVD_MAX_ENTRIES
#undef OUT_OF_RANGE
#undef CANNOT_INIT_PROBLEM
#undef OFFSET_IN_MGUD
#undef IS_MGUDBLOCK_DEF
#undef TOPNODE
#undef PVCOUNT
#undef SETPVCOUNT
#undef MAX_PERIODIC_OBJ
#undef CW_FREE
#undef CW_USED
#undef CE_FREE
#undef CE_USED
#undef CE_LOCKED
#undef CW_INIT
#undef CW_INIT_UNUSED
#undef CE_INIT
#undef CE_INIT_UNUSED
#undef _DEBUG_CW_
#undef CW_READ
#undef CW_READ_STATIC
#undef CW_WRITE
#undef CW_WRITE_STATIC
#undef ControlWord
#undef CW_READ
#undef CW_READ
#undef CW_WRITE
#undef StaticControlWord
#undef StaticControlWordMask
#undef CW_READ_STATIC
#undef CW_READ_STATIC
#undef CW_WRITE_STATIC
#undef LV_MOD_DEFAULT
#undef SIGNIFICANT_DIGITS
#undef COORDINATE_TO_KEY
#undef COORDINATE_TO_KEY
#undef VECTOR_OFFSET
#undef VOTYPE_SHIFT
#undef VOTYPE_LEN
#undef VOTYPE
#undef SETVOTYPE
#undef VTYPE_SHIFT
#undef VTYPE_LEN
#undef VTYPE
#undef SETVTYPE
#undef VDATATYPE_SHIFT
#undef VDATATYPE_LEN
#undef VDATATYPE
#undef SETVDATATYPE
#undef VCLASS_SHIFT
#undef VCLASS_LEN
#undef VCLASS
#undef SETVCLASS
#undef VNCLASS_SHIFT
#undef VNCLASS_LEN
#undef VNCLASS
#undef SETVNCLASS
#undef VNEW_SHIFT
#undef VNEW_LEN
#undef VNEW
#undef SETVNEW
#undef VCCUT_SHIFT
#undef VCCUT_LEN
#undef VCCUT
#undef SETVCCUT
#undef VCOUNT_SHIFT
#undef VCOUNT_LEN
#undef VCOUNT
#undef SETVCOUNT
#undef VECTORSIDE_SHIFT
#undef VECTORSIDE_LEN
#undef VECTORSIDE
#undef SETVECTORSIDE
#undef VCCOARSE_SHIFT
#undef VCCOARSE_LEN
#undef VCCOARSE
#undef SETVCCOARSE
#undef FINE_GRID_DOF_SHIFT
#undef FINE_GRID_DOF_LEN
#undef FINE_GRID_DOF
#undef SETFINE_GRID_DOF
#undef NEW_DEFECT_SHIFT
#undef NEW_DEFECT_LEN
#undef NEW_DEFECT
#undef SETNEW_DEFECT
#undef XFERVECTOR_SHIFT
#undef XFERVECTOR_LEN
#undef XFERVECTOR
#undef SETXFERVECTOR
#undef VPART_SHIFT
#undef VPART_LEN
#undef VPART
#undef SETVPART
#undef VACTIVE_SHIFT
#undef VACTIVE_LEN
#undef VACTIVE
#undef SETVACTIVE
#undef VCFLAG
#undef SETVCFLAG
#undef VCUSED
#undef SETVCUSED
#undef VOBJECT
#undef PPREDVC
#undef PPREDVC
#undef PREDVC
#undef SUCCVC
#undef VINDEX
#undef V_IN_DATATYPE
#undef VSKIPME
#undef VVECSKIP
#undef VFULLSKIP
#undef SETVSKIPME
#undef VECSKIP
#undef VECSKIPBIT
#undef SETVECSKIPBIT
#undef VSTART
#undef VISTART
#undef VVALUE
#undef VVALUEPTR
#undef VMYNODE
#undef VMYEDGE
#undef VMYELEMENT
#undef VUP
#undef SETVUP
#undef VDOWN
#undef SETVDOWN
#undef VBVD
#undef VMATCH
#undef CAST_NVECTOR
#undef CAST_EDVECTOR
#undef CAST_SVECTOR
#undef CAST_EVECTOR
#undef MATRIX_OFFSET
#undef MOFFSET_SHIFT
#undef MOFFSET_LEN
#undef MOFFSET
#undef SETMOFFSET
#undef MROOTTYPE_SHIFT
#undef MROOTTYPE_LEN
#undef MROOTTYPE
#undef SETMROOTTYPE
#undef MDESTTYPE_SHIFT
#undef MDESTTYPE_LEN
#undef MDESTTYPE
#undef SETMDESTTYPE
#undef MDIAG_SHIFT
#undef MDIAG_LEN
#undef MDIAG
#undef SETMDIAG
#undef MNEW_SHIFT
#undef MNEW_LEN
#undef MNEW
#undef SETMNEW
#undef CEXTRA_SHIFT
#undef CEXTRA_LEN
#undef CEXTRA
#undef SETCEXTRA
#undef MDOWN_SHIFT
#undef MDOWN_LEN
#undef MDOWN
#undef SETMDOWN
#undef MUP_SHIFT
#undef MUP_LEN
#undef MUP
#undef SETMUP
#undef MLOWER_SHIFT
#undef MLOWER_LEN
#undef MLOWER
#undef SETMLOWER
#undef MUPPER_SHIFT
#undef MUPPER_LEN
#undef MUPPER
#undef SETMUPPER
#undef MACTIVE_SHIFT
#undef MACTIVE_LEN
#undef MACTIVE
#undef SETMACTIVE
#undef MSIZE_SHIFT
#undef MSIZE_LEN
#undef MSIZEMAX
#undef MSIZE
#undef SETMSIZE
#undef MSIZEMAX
#undef MSIZE
#undef SETMSIZE
#undef MTYPE
#undef MUSED
#undef SETMUSED
#undef XFERMATX_SHIFT
#undef XFERMATX_LEN
#undef XFERMATX
#undef SETXFERMATX
#undef MINC
#undef MDEC
#undef MNEXT
#undef MDEST
#undef MADJ
#undef MROOT
#undef MMYCON
#undef MVALUE
#undef MVALUEPTR
#undef MDESTINDEX
#undef MSTRONG
#undef CMATRIX0
#undef CMATRIX1
#undef SETCUSED
#undef BVD_NR_ENTRIES
#undef BVD_INIT
#undef BVD_PUSH_ENTRY
#undef BVD_DISCARD_LAST_ENTRY
#undef BVD_INC_LAST_ENTRY
#undef BVD_DEC_LAST_ENTRY
#undef BVD_INIT_SEQ_READ
#undef BVD_READ_NEXT_ENTRY
#undef BVD_SET_ENTRY
#undef BVD_GET_ENTRY
#undef BVD_IS_SUB_BLOCK
#undef BLOCKVECTOR_OFFSET
#undef BVDOWNTYPE_SHIFT
#undef BVDOWNTYPE_LEN
#undef BVDOWNTYPE
#undef SETBVDOWNTYPE
#undef BVLEVEL_SHIFT
#undef BVLEVEL_LEN
#undef BVLEVEL
#undef SETBVLEVEL
#undef BVTVTYPE_SHIFT
#undef BVTVTYPE_LEN
#undef BVTVTYPE
#undef SETBVTVTYPE
#undef BVORIENTATION_SHIFT
#undef BVORIENTATION_LEN
#undef BVORIENTATION
#undef SETBVORIENTATION
#undef BVNUMBER
#undef BVUSERDATA
#undef BVPRED
#undef BVSUCC
#undef BVFIRSTVECTOR
#undef BVLASTVECTOR
#undef BVENDVECTOR
#undef BVNUMBEROFVECTORS
#undef BVDOWNVECTOR
#undef BVDOWNBV
#undef BVDOWNBVLAST
#undef BVDOWNBVEND
#undef BV_GEN_F
#undef BV_GEN_L
#undef BV_GEN_C
#undef SETBV_GC
#undef BV_IS_GC
#undef BV_GEN
#undef BV_CYC
#undef SET_ORD_GCL
#undef ORD_GEN
#undef ORD_CYC
#undef ORD_LIN
#undef BV_IS_EMPTY
#undef BV_IS_LEAF_BV
#undef BV_IS_DIAG_BV
#undef LIOBJ
#undef COOBJ
#undef GENERAL_CW
#undef GENERAL_OFFSET
#undef OBJ_SHIFT
#undef OBJ_LEN
#undef OBJT
#undef SETOBJT
#undef OBJT_MAX
#undef USED_SHIFT
#undef USED_LEN
#undef USED
#undef SETUSED
#undef THEFLAG_SHIFT
#undef THEFLAG_LEN
#undef THEFLAG
#undef SETTHEFLAG
#undef LEVEL_SHIFT
#undef LEVEL_LEN
#undef LEVEL
#undef SETLEVEL
#undef TAG_SHIFT
#undef TAG_LEN
#undef TAG
#undef SETTAG
#undef REF2TAG
#undef CTRL
#undef ID
#undef VERTEX_OFFSET
#undef MOVE_SHIFT
#undef MOVE_LEN
#undef MOVE
#undef SETMOVE
#undef MOVED_SHIFT
#undef MOVED_LEN
#undef MOVED
#undef SETMOVED
#undef ONEDGE_SHIFT
#undef ONEDGE_LEN
#undef ONEDGE
#undef SETONEDGE
#undef ONSIDE_SHIFT
#undef ONSIDE_LEN
#undef ONSIDE
#undef SETONSIDE
#undef ONNBSIDE_SHIFT
#undef ONNBSIDE_LEN
#undef ONNBSIDE
#undef SETONNBSIDE
#undef NOOFNODE_SHIFT
#undef NOOFNODE_LEN
#undef NOOFNODEMAX
#undef NOOFNODE
#undef SETNOOFNODE
#undef INCNOOFNODE
#undef DECNOOFNODE
#undef PREDV
#undef SUCCV
#undef CVECT
#undef XC
#undef YC
#undef ZC
#undef LCVECT
#undef XI
#undef ETA
#undef NU
#undef VDATA
#undef VFATHER
#undef V_BNDP
#undef PARHDRV
#undef NODE_OFFSET
#undef NTYPE_SHIFT
#undef NTYPE_LEN
#undef NTYPE
#undef SETNTYPE
#undef NSUBDOM_SHIFT
#undef NSUBDOM_LEN
#undef NSUBDOM
#undef SETNSUBDOM
#undef NPROP_SHIFT
#undef NPROP_LEN
#undef NPROP
#undef SETNPROP
#undef MODIFIED_SHIFT
#undef MODIFIED_LEN
#undef MODIFIED
#undef SETMODIFIED
#undef NCLASS_SHIFT
#undef NCLASS_LEN
#undef NCLASS
#undef SETNCLASS
#undef NNCLASS_SHIFT
#undef NNCLASS_LEN
#undef NNCLASS
#undef SETNNCLASS
#undef NO_DELETE_OVERLAP2_LEN
#undef NO_DELETE_OVERLAP2
#undef SETNO_DELETE_OVERLAP2
#undef PREDN
#undef SUCCN
#undef START
#undef NFATHER
#undef SETNFATHER
#undef NFATHEREDGE
#undef NFATHER
#undef NFATHEREDGE
#undef SETNFATHEREDGE
#undef CORNERTYPE
#undef MIDTYPE
#undef SIDETYPE
#undef CENTERTYPE
#undef SONNODE
#undef MYVERTEX
#undef NDATA
#undef NVECTOR
#undef NODE_ELEMENT_LIST
#undef ELEMENT_PTR
#undef LINK_OFFSET
#undef LOFFSET_SHIFT
#undef LOFFSET_LEN
#undef LOFFSET
#undef SETLOFFSET
#undef NBNODE
#undef NEXT
#undef LDATA
#undef MATELEM
#undef MYEDGE
#undef REVERSE
#undef LELEM
#undef SET_LELEM
#undef EDGE_OFFSET
#undef NO_OF_ELEM_SHIFT
#undef NO_OF_ELEM_LEN
#undef NO_OF_ELEM_MAX
#undef NO_OF_ELEM
#undef SET_NO_OF_ELEM
#undef INC_NO_OF_ELEM
#undef DEC_NO_OF_ELEM
#undef AUXEDGE_SHIFT
#undef AUXEDGE_LEN
#undef AUXEDGE
#undef SETAUXEDGE
#undef EDGENEW_SHIFT
#undef EDGENEW_LEN
#undef EDGENEW
#undef SETEDGENEW
#undef EDSUBDOM_SHIFT
#undef EDSUBDOM_LEN
#undef EDSUBDOM
#undef SETEDSUBDOM
#undef LINK0
#undef LINK1
#undef MIDNODE
#undef EDDATA
#undef EDVECTOR
#undef ELEMENT_OFFSET
#undef FLAG_OFFSET
#undef PROPERTY_OFFSET
#undef ECLASS_SHIFT
#undef ECLASS_LEN
#undef ECLASS
#undef SETECLASS
#undef NSONS_SHIFT
#undef NSONS_LEN
#undef NSONS
#undef SETNSONS
#undef NEWEL_SHIFT
#undef NEWEL_LEN
#undef NEWEL
#undef SETNEWEL
#undef SUBDOMAIN_SHIFT
#undef SUBDOMAIN_LEN
#undef SUBDOMAIN
#undef SETSUBDOMAIN
#undef NODEORD_SHIFT
#undef NODEORD_LEN
#undef NODEORD
#undef SETNODEORD
#undef PROP_SHIFT
#undef PROP_LEN
#undef PROP
#undef SETPROP
#undef PARTITION
#undef PARHDRE
#undef SIDES_OF_ELEM
#undef EDGES_OF_ELEM
#undef CORNERS_OF_ELEM
#undef LOCAL_COORD_OF_ELEM
#undef SONS_OF_ELEM
#undef EDGES_OF_SIDE
#undef CORNERS_OF_SIDE
#undef CORNERS_OF_EDGE
#undef EDGE_OF_SIDE
#undef EDGE_OF_TWO_SIDES
#undef CORNER_OF_SIDE
#undef CORNER_OF_EDGE
#undef EDGE_WITH_CORNERS
#undef SIDE_WITH_EDGE
#undef CORNER_OF_SIDE_INV
#undef EDGES_OF_CORNER
#undef CORNER_OF_OPPEDGE
#undef CORNER_OPP_TO_SIDE
#undef OPPOSITE_EDGE
#undef SIDE_OPP_TO_CORNER
#undef EDGE_OF_CORNER
#undef CTRL2
#undef FLAG
#undef SUCCE
#undef PREDE
#undef CENTERNODE
#undef CORNER
#undef EFATHER
#undef SON
#undef NBELEM
#undef NBELEM
#undef ELEM_BNDS
#undef EVECTOR
#undef SVECTOR
#undef EDATA
#undef SIDE_ON_BND
#undef INNER_SIDE
#undef INNER_BOUNDARY
#undef EDGE_ON_BND
#undef EDGE_ON_BND
#undef SET_CENTERNODE
#undef SET_CORNER
#undef SET_EFATHER
#undef SET_SON
#undef SET_NBELEM
#undef VOID_NBELEM
#undef SET_NBELEM
#undef VOID_NBELEM
#undef SET_BNDS
#undef SET_EVECTOR
#undef SET_SVECTOR
#undef SET_EDATA
#undef SideBndCond
#undef Vertex_BndCond
#undef CORNER_OF_EDGE_PTR
#undef CORNER_OF_SIDE_PTR
#undef INNER_SIZE_TAG
#undef BND_SIZE_TAG
#undef MAPPED_INNER_OBJT_TAG
#undef MAPPED_BND_OBJT_TAG
#undef SIDES_OF_TAG
#undef EDGES_OF_TAG
#undef CORNERS_OF_TAG
#undef LOCAL_COORD_OF_TAG
#undef SONS_OF_TAG
#undef EDGES_OF_SIDE_TAG
#undef CORNERS_OF_SIDE_TAG
#undef EDGE_OF_SIDE_TAG
#undef EDGE_OF_TWO_SIDES_TAG
#undef CORNER_OF_SIDE_TAG
#undef CORNER_OF_EDGE_TAG
#undef EDGE_WITH_CORNERS_TAG
#undef SIDE_WITH_EDGE_TAG
#undef CORNER_OF_SIDE_INV_TAG
#undef EDGES_OF_CORNER_TAG
#undef CORNER_OF_OPPEDGE_TAG
#undef CORNER_OPP_TO_SIDE_TAG
#undef OPPOSITE_EDGE_TAG
#undef SIDE_OPP_TO_CORNER_TAG
#undef EDGE_OF_CORNER_TAG
#undef SIDES_OF_REF
#undef EDGES_OF_REF
#undef CORNERS_OF_REF
#undef LOCAL_COORD_OF_REF
#undef EDGES_OF_SIDE_REF
#undef CORNERS_OF_SIDE_REF
#undef EDGE_OF_SIDE_REF
#undef EDGE_OF_TWO_SIDES_REF
#undef CORNER_OF_SIDE_REF
#undef CORNER_OF_EDGE_REF
#undef EDGE_WITH_CORNERS_REF
#undef SIDE_WITH_EDGE_REF
#undef CORNER_OF_SIDE_INV_REF
#undef EDGES_OF_CORNER_REF
#undef CORNER_OF_OPPEDGE_REF
#undef CORNER_OPP_TO_SIDE_REF
#undef OPPOSITE_EDGE_REF
#undef SIDE_OPP_TO_CORNER_REF
#undef EDGE_OF_CORNER_REF
#undef GRID_OFFSET
#undef GRID_STATUS_OFFSET
#undef GLEVEL
#undef GATTR
#undef GFORMAT
#undef SETGLOBALGSTATUS
#undef GSTATUS
#undef RESETGSTATUS
#undef PFIRSTELEMENT
#undef PRIO_FIRSTELEMENT
#undef LISTPART_FIRSTELEMENT
#undef FIRSTELEMENT
#undef PLASTELEMENT
#undef PRIO_LASTELEMENT
#undef LISTPART_LASTELEMENT
#undef LASTELEMENT
#undef FIRSTELEMENT
#undef PFIRSTELEMENT
#undef LASTELEMENT
#undef PLASTELEMENT
#undef PFIRSTVERTEX
#undef PRIO_FIRSTVERTEX
#undef LISTPART_FIRSTVERTEX
#undef FIRSTVERTEX
#undef SFIRSTVERTEX
#undef PLASTVERTEX
#undef PRIO_LASTVERTEX
#undef LISTPART_LASTVERTEX
#undef LASTVERTEX
#undef FIRSTVERTEX
#undef PFIRSTVERTEX
#undef SFIRSTVERTEX
#undef LASTVERTEX
#undef PLASTVERTEX
#undef FIRSTELEMSIDE
#undef PFIRSTNODE
#undef PRIO_FIRSTNODE
#undef LISTPART_FIRSTNODE
#undef FIRSTNODE
#undef SFIRSTNODE
#undef PLASTNODE
#undef PRIO_LASTNODE
#undef LISTPART_LASTNODE
#undef LASTNODE
#undef FIRSTNODE
#undef PFIRSTNODE
#undef SFIRSTNODE
#undef LASTNODE
#undef PLASTNODE
#undef PFIRSTVECTOR
#undef PRIO_FIRSTVECTOR
#undef LISTPART_FIRSTVECTOR
#undef FIRSTVECTOR
#undef SFIRSTVECTOR
#undef PLASTVECTOR
#undef PRIO_LASTVECTOR
#undef LISTPART_LASTVECTOR
#undef LASTVECTOR
#undef FIRSTVECTOR
#undef PFIRSTVECTOR
#undef SFIRSTVECTOR
#undef LASTVECTOR
#undef PLASTVECTOR
#undef GFIRSTBV
#undef GLASTBV
#undef UPGRID
#undef DOWNGRID
#undef MYMG
#undef NV
#undef NN
#undef NT
#undef NVEC
#undef NV_PRIO
#undef NN_PRIO
#undef NT_PRIO
#undef NVEC_PRIO
#undef NE
#undef NS
#undef NC
#undef VEC_DEF_IN_OBJ_OF_GRID
#undef NIMAT
#undef NELIST_DEF_IN_GRID
#undef EDATA_DEF_IN_GRID
#undef NDATA_DEF_IN_GRID
#undef MULTIGRID_STATUS_OFFSET
#undef MGSTATUS
#undef RESETMGSTATUS
#undef MG_MAGIC_COOKIE
#undef VIDCNT
#undef NIDCNT
#undef EIDCNT
#undef TOPLEVEL
#undef BOTTOMLEVEL
#undef CURRENTLEVEL
#undef FULLREFINELEVEL
#undef MGFORMAT
#undef DATAFORMAT
#undef MG_BVP
#undef MG_BVPD
#undef MGBNDSEGDESC
#undef MGVERTEX
#undef MGNOOFCORNERS
#undef MGHEAP
#undef MG_NPROPERTY
#undef GRID_ON_LEVEL
#undef ELEMS_OF_NODE_MAX
#undef NDELEM_BLKS_MAX
#undef NO_NODES_OF_BLK
#undef MGNDELEMPTRARRAY
#undef MGNDELEMBLK
#undef MGNDELEMOFFS
#undef MGNDELEMBLKENTRY
#undef SELECTIONSIZE
#undef SELECTIONMODE
#undef SELECTIONOBJECT
#undef MGNAME
#undef MG_USER_HEAP
#undef GEN_MGUD
#undef GEN_MGUD_ADR
#undef VEC_DEF_IN_OBJ_OF_MG
#undef NELIST_DEF_IN_MG
#undef EDATA_DEF_IN_MG
#undef NDATA_DEF_IN_MG
#undef MG_GENPURP
#undef MG_SAVED
#undef MG_FILENAME
#undef MG_COARSE_FIXED
#undef MG_MARK_KEY
#undef FMT_ELEM_DATA
#undef FMT_NODE_DATA
#undef FMT_NODE_ELEM_LIST
#undef FMT_S_VERTEX
#undef FMT_S_MG
#undef FMT_S_VEC_TP
#undef FMT_VTYPE_NAME
#undef FMT_S_MAT_TP
#undef FMT_S_MATPTR
#undef FMT_S_IMAT_TP
#undef FMT_CONN_DEPTH_TP
#undef FMT_CONN_DEPTH_PTR
#undef FMT_CONN_DEPTH_MAX
#undef FMT_NB_DEPTH
#undef FMT_PR_VERTEX
#undef FMT_PR_GRID
#undef FMT_PR_MG
#undef FMT_PR_VEC
#undef FMT_PR_MAT
#undef FMT_PO2T
#undef FMT_T2P
#undef FMT_TYPE_IN_PART
#undef FMT_T2O
#undef FMT_TYPE_USES_OBJ
#undef FMT_USES_OBJ
#undef FMT_MAX_PART
#undef FMT_MAX_TYPE
#undef FMT_N2T
#undef FMT_SET_N2T
#undef FMT_T2N
#undef GM_TAKE_SKIP
#undef GM_TAKE_NONSKIP
#undef __COMPILER__
#undef SMALL_FAC
#undef ARCH_LONG_TIMER
#undef CURRENT_TIME
#undef CURRENT_TIME_LONG
#undef ARCH_DIFF_TIMER
#undef _fmt_le
#undef _fmt_lE
#undef _fmt_lg
#undef _fmt_lG
#undef _fmt_lf
#undef exactly
#undef this
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef malloc
#undef free
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef const
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef TICKS_PER_SEC
#undef CURRENT_TIME
#undef CURRENT_TIME
#undef CURRENT_TIME
#undef ARCH_DIFF_TIMER
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef __SWAPBYTES__
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CLOCKS_PER_SEC
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CLOCKS_PER_SEC
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef ARCHNAME
#undef USES_UNIVERSAL_HEADERS
#undef __MWCW_oldVersion__
#undef SHORT
#undef INT
#undef FLOAT
#undef DOUBLE
#undef COORD
#undef SCREEN_COORD
#undef malloc
#undef free
#undef ALIGNMENT
#undef ALIGNMASK
#undef F77SYM
#undef CURRENT_TIME
#undef _fmt_lg
#undef _fmt_lG
#undef _fmt_le
#undef _fmt_lE
#undef _fmt_lf
#undef __MACINTOSH__
#undef ARCH_VERSION
#undef MAX_S
#undef MAX_I
#undef MAX_F
#undef SMALL_F
#undef MAX_D
#undef SMALL_D
#undef MAX_C
#undef SMALL_C
#undef __HEAPS__
#undef MEM_SIZE_ULL
#undef MIN_HEAP_SIZE
#undef MARK_STACK_SIZE
#undef MAXFREEOBJECTS
#undef MarkTmpMem
#undef GetTmpMem
#undef ReleaseTmpMem
#undef MAXNBLOCKS
#undef SIZE_UNKNOWN
#undef SIZEOF_VHM
#undef BHM_OK
#undef BLOCK_NOT_DEFINED
#undef OFFSET_IN_HEAP
#undef TOTUSED_IN_HEAP
#undef IS_BLOCK_DEFINED
#undef CEIL
#undef UG_NAMESPACE_H
#undef START_UG_NAMESPACE
#undef END_NAMESPACE
#undef NS_PREFIX
#undef USING_UG_NAMESPACE
#undef START_UGDIM_NAMESPACE
#undef USING_UGDIM_NAMESPACE
#undef USING_UG_NAMESPACES
#undef NS_DIM_PREFIX
#undef START_UGDIM_NAMESPACE
#undef USING_UGDIM_NAMESPACE
#undef USING_UG_NAMESPACES
#undef NS_DIM_PREFIX
#undef NS_DIM_PREFIX
#undef __UGENV__
#undef NAMELENSTR
#undef SEARCHALL
#undef DIRSEP
#undef ROOT_DIR
#undef ENVITEM_DOWN
#undef ENVDIR_DOWN
#undef NEXT_ENVITEM
#undef PREV_ENVITEM
#undef ENVITEM_TYPE
#undef IS_ENVDIR
#undef ENVITEM_NAME
#undef ENVITEM_LOCKED
#undef __MISC__
#undef PI
#undef KBYTE
#undef MBYTE
#undef GBYTE
#undef ABS
#undef MIN
#undef MAX
#undef POW2
#undef ABSDIFF
#undef SIGNUM
#undef FSIGNUM
#undef DSIGNUM
#undef EVEN
#undef ODD
#undef SWAP
#undef QUOT
#undef SET_FLAG
#undef CLEAR_FLAG
#undef READ_FLAG
#undef HiWrd
#undef LoWrd
#undef SetHiWrd
#undef SetLoWrd
#undef CONCAT3
#undef CONCAT3_AUX
#undef CONCAT4
#undef CONCAT4_AUX
#undef CONCAT5
#undef CONCAT5_AUX
#undef XCAT
#undef XCAT3
#undef CAT
#undef CAT3
#undef XSTR
#undef STR
#undef YES
#undef ON
#undef NO
#undef OFF
#undef TRUE
#undef FALSE
#undef BOOL_2_YN
#undef BOOL_2_TF
#undef BOOL_2_NF
#undef STR_SWITCH
#undef STR_CASE
#undef STR_BREAK
#undef STR_DEFAULT
#undef STR_SWITCH_END
#undef __DEBUG__
#undef REP_ERR_MAX
#undef DEBUG_TIME_MAX
#undef HEAPCHECK
#undef IFDEBUG
#undef PRINTDEBUG
#undef PRINTDEBUG_EXT
#undef ENDDEBUG
#undef RETURN
#undef SETHEAPFAULT
#undef HEAPFAULT
#undef ASSERT
#undef REP_ERR_INC
#undef REP_ERR_RETURN
#undef REP_ERR_RETURN_PTR
#undef REP_ERR_RETURN_VOID
#undef REP_ERR_GOTO
#undef REP_ERR_RETURN
#undef REP_ERR_RETURN_PTR
#undef REP_ERR_RETURN_VOID
#undef REP_ERR_GOTO
#undef REP_ERR_ENCOUNTERED
#undef REP_ERR_RESET
#undef REP_ERR_FILE
#undef DEBUG_TIME_RESET
#undef DEBUG_TIME_INC
#undef DEBUG_TIME
#undef IFDEBUG
#undef ENDDEBUG
#undef PRINTDEBUG
#undef PRINTDEBUG_EXT
#undef RETURN
#undef HEAPFAULT
#undef ASSERT
#undef REP_ERR_RETURN
#undef REP_ERR_RETURN_PTR
#undef REP_ERR_RETURN_VOID
#undef REP_ERR_GOTO
#undef REP_ERR_ENCOUNTERED
#undef REP_ERR_INC
#undef REP_ERR_RESET
#undef REP_ERR_FILE
#undef DEBUG_TIME_RESET
#undef DEBUG_TIME_INC
#undef DEBUG_TIME
#undef PrintDebug
#undef __GENERAL__
#undef UG_VERSION
#undef UG_RCS_STRING
#undef UGRCSSTRING
#undef UGRCSSTRINGAUX
#undef RCSID
#undef RCSIDAUX
#undef RCSID1
#undef RCSIDAUX1
#undef RCS_ID
#undef RCS_ID_AUX
#undef RCS_ID1
#undef RCS_ID_AUX1
#undef __DOMAIN__
#undef DOM_LOC_X
#undef DOM_LOC_Y
#undef DOM_PARAM_OFFSET
#undef DOM_EVAL_SD_UNKNOWN
#undef BVPD_NAME
#undef BVPD_MIDPOINT
#undef BVPD_RADIUS
#undef BVPD_CONVEX
#undef BVPD_NSUBDOM
#undef BVPD_NPARTS
#undef BVPD_CONFIG
#undef BVPD_S2P_PTR
#undef BVPD_S2P
#undef BVPD_NCOEFFF
#undef BVPD_NUSERF
#undef __PARGM_H__
#undef EDGE_WITH_DDDHDR
#undef PRIO2LISTPART
#undef LISTPART2PRIO
#undef PRIO2INDEX
#undef PARHDR
#undef GETGID
#undef GETGID
#undef CDBG
#undef CDBG
#undef PRIO2LISTPART
#undef LISTPART2PRIO
#undef PRIO2INDEX
#undef CDBG
#undef GRID_ATTR
#undef ATTR_TO_GLEVEL
#undef ID_FMT
#undef ID_FFMT
#undef ID_PRT
#undef ID_FMTE
#undef ID_FFMTE
#undef ID_PRTE
#undef ID_FMTX
#undef ID_FFMTX
#undef ID_PRTX
#undef VID_FMT
#undef VID_FFMT
#undef VID_PRT
#undef VID_FMTE
#undef VID_FFMTE
#undef VID_PRTE
#undef VID_FMTX
#undef VID_FFMTX
#undef VID_PRTX
#undef EID_FMT
#undef EID_FFMT
#undef EID_PRT
#undef EID_FMTE
#undef EID_FFMTE
#undef EID_PRTE
#undef EID_FMTX
#undef EID_FFMTX
#undef EID_PRTX
#undef VINDEX_FMT
#undef VINDEX_FFMT
#undef VINDEX_PRT
#undef VINDEX_FMTE
#undef VINDEX_FFMTE
#undef VINDEX_PRTE
#undef VINDEX_FMTX
#undef VINDEX_FFMTX
#undef VINDEX_PRTX
#undef EDID_FMT
#undef EDID_FFMT
#undef EDID_PRT
#undef EDID_FMTE
#undef EDID_FFMTE
#undef EDID_PRTE
#undef EDID_FMTX
#undef EDID_FFMTX
#undef EDID_PRTX
#undef EDID_FMT
#undef EDID_FFMT
#undef EDID_PRT
#undef EDID_FMTE
#undef EDID_FFMTE
#undef EDID_PRTE
#undef EDID_FMTX
#undef EDID_FFMTX
#undef EDID_PRTX
#undef PFMT
#undef PAR
#undef ENDPAR
#undef ID_FMT
#undef ID_FFMT
#undef ID_PRT
#undef ID_FMTE
#undef ID_FFMTE
#undef ID_PRTE
#undef ID_FMTX
#undef ID_FFMTX
#undef ID_PRTX
#undef VID_FMT
#undef VID_FFMT
#undef VID_PRT
#undef VID_FMTE
#undef VID_FFMTE
#undef VID_PRTE
#undef VID_FMTX
#undef VID_FFMTX
#undef VID_PRTX
#undef EID_FMT
#undef EID_FFMT
#undef EID_PRT
#undef EID_FMTE
#undef EID_FFMTE
#undef EID_PRTE
#undef EID_FMTX
#undef EID_FFMTX
#undef EID_PRTX
#undef VINDEX_FMT
#undef VINDEX_FFMT
#undef VINDEX_PRT
#undef VINDEX_FMTE
#undef VINDEX_FFMTE
#undef VINDEX_PRTE
#undef VINDEX_FMTX
#undef VINDEX_FFMTX
#undef VINDEX_PRTX
#undef EDID_FMT
#undef EDID_FFMT
#undef EDID_PRT
#undef EDID_FMTE
#undef EDID_FFMTE
#undef EDID_PRTE
#undef EDID_FMTX
#undef EDID_FFMTX
#undef EDID_PRTX
#undef PFMT
#undef GIDFMT
#undef EGID
#undef GID
#undef VGID
#undef PAR
#undef ENDPAR
#undef GetAllSons
#undef EMASTER
#undef EGHOST
#undef EHGHOST
#undef EVGHOST
#undef EPRIO
#undef SETEPRIO
#undef EMASTERPRIO
#undef EPROCLIST
#undef ENCOPIES
#undef PARTITION
#undef MASTER
#undef GHOST
#undef HGHOST
#undef VGHOST
#undef PRIO
#undef EPRIO
#undef VXPRIO
#undef SETPRIO
#undef PROCLIST
#undef NCOPIES
#undef SETVXPRIO
#undef DDD_OBJ
#undef DDD_IdentifyBegin
#undef DDD_IdentifyEnd
#undef DDD_IdentifyNumber
#undef DDD_IFAOneway
#undef DDD_PrioritySet
#undef Broadcast
#undef UG_GlobalSumINT
#undef UG_GlobalMaxINT
#undef UG_GlobalMinINT
#undef UG_GlobalSumNINT
#undef UG_GlobalMaxNINT
#undef UG_GlobalMinNINT
#undef UG_GlobalSumDOUBLE
#undef UG_GlobalMaxDOUBLE
#undef UG_GlobalMinDOUBLE
#undef UG_GlobalSumNDOUBLE
#undef UG_GlobalMaxNDOUBLE
#undef UG_GlobalMinNDOUBLE
#undef __CW__
#undef MAX_CONTROL_WORDS
#undef MAX_CONTROL_ENTRIES
#undef __ELEMENTS__
#undef TAGS
#undef __STD_DOMAIN__
#undef CORNERS_OF_BND_SEG
#undef DIMENSION_H
#undef __TWODIM__
#undef DIM
#undef DIM_OF_BND
#undef __THREEDIM__
#undef DIM
#undef DIM_OF_BND
#undef __INITUG__
#undef __COMMANDS__
#undef NO_OPTION_CHECK
#undef __CMDLINE__
#undef DONE
#undef OKCODE
#undef QUITCODE
#undef PARAMERRORCODE
#undef CMDERRORCODE
#undef INTERRUPTCODE
#undef FATAL
#undef MAXOPTIONS
#undef OPTIONBUFFERLEN
#undef __FORMATS__
#undef MAX_SUB
#undef V_COMP_NAMES
#undef M_COMP_NAMES
#undef SUBV_NAME
#undef SUBV_NCOMPS
#undef SUBV_NCOMP
#undef SUBV_COMP
#undef SUBM_NAME
#undef SUBM_RCOMPS
#undef SUBM_CCOMPS
#undef SUBM_RCOMP
#undef SUBM_CCOMP
#undef SUBM_MCMPPTR
#undef SUBM_MCMPPTR_OF_MTYPE
#undef SUBM_MCMP_OF_MTYPE
#undef SUBM_COMPS
#undef SUBM_COMP
#undef VT_COMPS
#undef VT_COMP
#undef VT_COMPNAMES
#undef VT_COMPNAME
#undef VT_NID
#undef VT_IDENT_PTR
#undef VT_IDENT
#undef VT_SUB
#undef VT_NSUB
#undef MT_RCOMPS
#undef MT_RCOMP
#undef MT_CCOMPS
#undef MT_CCOMP
#undef MT_COMPS
#undef MT_COMP
#undef MT_MCMPPTR
#undef MT_MCMPPTR_OF_MTYPE
#undef MT_MCMP_OF_MTYPE
#undef MT_COMPNAMES
#undef MT_COMPNAME
#undef MT_SUB
#undef MT_NSUB
#undef MT_SM
#undef MT_SMP
#undef __UDM__
#undef NVECTYPES
#undef NMATTYPES
#undef NMATTYPES_NORMAL
#undef MTP
#undef DMTP
#undef MTYPE_RT
#undef MTYPE_CT
#undef MAX_SINGLE_VEC_COMP
#undef MAX_SINGLE_MAT_COMP
#undef MAX_VEC_COMP
#undef MAX_MAT_COMP
#undef MAX_MAT_COMP_TOTAL
#undef NVECOFFSETS
#undef NMATOFFSETS
#undef DEFAULT_NAMES
#undef NO_IDENT
#undef FULL_TPLT
#undef GENERATED_NAMES_SEPERATOR
#undef VD_MG
#undef VD_ISDEF_IN_TYPE
#undef VD_NCMPPTR
#undef VD_NCMPS_IN_TYPE
#undef VD_CMP_OF_TYPE
#undef VD_CMPPTR_OF_TYPE
#undef VD_NID
#undef VD_IDENT_PTR
#undef VD_IDENT
#undef VD_DATA_TYPES
#undef VD_OBJ_USED
#undef VD_IS_SCALAR
#undef VD_SCALCMP
#undef VD_SCALTYPEMASK
#undef VD_OFFSETPTR
#undef VD_OFFSET
#undef VD_NCOMP
#undef VD_MINTYPE
#undef VD_MAXTYPE
#undef VD_SUCC_COMP
#undef MCMP
#undef MCMP_I
#undef MCMP_J
#undef MD_MG
#undef MD_ISDEF_IN_MTYPE
#undef MD_ISDEF_IN_RT_CT
#undef MD_ROWPTR
#undef MD_ROWS_IN_MTYPE
#undef MD_ROWS_IN_RT_CT
#undef MD_COLPTR
#undef MD_COLS_IN_MTYPE
#undef MD_COLS_IN_RT_CT
#undef MD_NCMPS_IN_MTYPE
#undef MD_NCMPS_IN_RT_CT
#undef MD_MCMPPTR
#undef MD_MCMPPTR_OF_MTYPE
#undef MD_MCMP_OF_MTYPE
#undef MD_MCMPPTR_OF_RT_CT
#undef MD_MCMP_OF_RT_CT
#undef MD_IJ_CMP_OF_MTYPE
#undef MD_IJ_CMP_OF_RT_CT
#undef MD_ROW_DATA_TYPES
#undef MD_COL_DATA_TYPES
#undef MD_ROW_OBJ_USED
#undef MD_COL_OBJ_USED
#undef MD_SM
#undef MD_SMP
#undef MD_IS_SPARSE
#undef MD_IS_SCALAR
#undef MD_SCALCMP
#undef MD_SCAL_RTYPEMASK
#undef MD_SCAL_CTYPEMASK
#undef MD_OFFSETPTR
#undef MD_MTYPE_OFFSET
#undef MD_RT_CT_OFFSET
#undef MD_SUCC_COMP
#undef VS_CMP_AT_OFFSET
#undef VS_CMP_OF_TYPE
#undef VM_COMP_NAMEPTR
#undef VM_COMP_NAME
#undef VM_COMPPTR
#undef VM_LOCKED
#undef EVM_LOCKED
#undef SPID_NVD_MAX
#undef SPID_NMD_MAX
#undef SPID_FORTH
#undef SPID_BACK
#undef SPID_NVD
#undef SPID_VD
#undef SPID_VDI
#undef SPID_NMD
#undef SPID_MD
#undef SPID_MDI
#undef READ_VEC_CONS_FLAG
#undef SET_VEC_CONS__FLAG
#undef CLEAR_VEC_CONS__FLAG
#undef READ_VEC_COLLECT_FLAG
#undef SET_VEC_COLLECT__FLAG
#undef CLEAR_VEC_COLLECT__FLAG
#undef EXTENSION_MAX
#undef EVDD_E
#undef EVDD_E_PTR
#undef EVD_NCOMP
#undef EMDD_EE
#undef EMDD_EE_PTR
#undef VD_ncmps_in_otype
#undef VD_cmp_of_otype
#undef VD_cmpptr_of_otype
#undef VD_cmpptr_of_otype_mod
#undef VD_ncmp_cmpptr_of_otype
#undef MD_rows_in_ro_co
#undef MD_cols_in_ro_co
#undef MD_rows_cols_in_ro_co
#undef MD_mcmp_of_ro_co
#undef MD_mcmpptr_of_ro_co
#undef MD_mcmpptr_of_ro_co_mod
#undef MD_nr_nc_mcmpptr_of_ro_co
#undef __SM__
#undef __UG__
#undef __UG__
#undef __SHAPES__
#undef DNDS
#undef DNDT
#undef CORNER_COORDINATES_TRIANGLE
#undef COPY_COORDINATES_TRIANGLE
#undef CORNER_COORDINATES_QUADRILATERAL
#undef COPY_COORDINATES_QUADRILATERAL
#undef CORNER_COORDINATES
#undef COPY_CORNER_COORDINATES
#undef LOCAL_TO_GLOBAL_TRIANGLE
#undef LOCAL_TO_GLOBAL_QUADRILATERAL
#undef LOCAL_TO_GLOBAL_2D
#undef AREA_OF_TRIANGLE
#undef AREA_OF_QUADRILATERAL
#undef AREA_OF_ELEMENT_2D
#undef AREA_OF_REF_2D
#undef TRANSFORMATION_OF_TRIANGLE
#undef TRANSFORMATION_OF_QUADRILATERAL
#undef TRANSFORMATION_2D
#undef SIDE_NORMAL_2D
#undef CORNER_COORDINATES_TETRAHEDRON
#undef COPY_COORDINATES_TETRAHEDRON
#undef CORNER_COORDINATES_PYRAMID
#undef COPY_COORDINATES_PYRAMID
#undef CORNER_COORDINATES_PRISM
#undef COPY_COORDINATES_PRISM
#undef CORNER_COORDINATES_HEXAHEDRON
#undef COPY_COORDINATES_HEXAHEDRON
#undef CORNER_COORDINATES
#undef COPY_CORNER_COORDINATES
#undef LOCAL_TO_GLOBAL_TETRAHEDRON
#undef LOCAL_TO_GLOBAL_PYRAMID
#undef LOCAL_TO_GLOBAL_PRISM
#undef LOCAL_TO_GLOBAL_HEXAHEDRON
#undef LOCAL_TO_GLOBAL_3D
#undef AREA_OF_TETRAHEDRON
#undef AREA_OF_PYRAMID
#undef AREA_OF_PRISM
#undef AREA_OF_HEXAHEDRON
#undef AREA_OF_ELEMENT_3D
#undef AREA_OF_REF_3D
#undef TRANSFORMATION_OF_TETRAHEDRON
#undef TRANSFORMATION_OF_PYRAMID
#undef TRANSFORMATION_OF_PRISM
#undef TRANSFORMATION_OF_HEXAHEDRON
#undef TRANSFORMATION_3D
#undef SIDE_NORMAL_3D
#undef LOCAL_TO_GLOBAL
#undef AREA_OF_ELEMENT
#undef AREA_OF_REF
#undef TRANSFORMATION
#undef SIDE_NORMAL
#undef TRANSFORMATION_BND
#undef LOCAL_TO_GLOBAL_BND
#undef AREA_OF_ELEMENT_BND
#undef AREA_OF_REF_BND
#undef LOCAL_TO_GLOBAL
#undef AREA_OF_ELEMENT
#undef AREA_OF_REF
#undef TRANSFORMATION
#undef SIDE_NORMAL
#undef INVERSE_TRANSFORMATION
#undef __EVM__
#undef _X_
#undef _Y_
#undef _Z_
#undef SQRT
#undef POW
#undef ISNaN
#undef COPY_SC_TO_SH
#undef CP_SUBTRACT
#undef CP_LIMCOMB
#undef CP_SCALARPRODUCT
#undef CP_EUKLIDNORM
#undef V1_LINCOMB
#undef V1_SET
#undef V1_COPY
#undef V1_SUBTRACT
#undef V1_ADD
#undef V1_ADD1
#undef V1_AVG2
#undef V1_AVG3
#undef V1_AVG4
#undef V1_SCALE
#undef V1_SCALEADD1
#undef V1_SCALESET
#undef V1_VECTOR_PRODUCT
#undef V1_COMPARE
#undef V1_ISEQUAL
#undef V1_EUKLIDNORM
#undef V1_EUKLIDNORM_OF_DIFF
#undef V1_CLEAR
#undef V1_SCALAR_PRODUCT
#undef V1_SCAL_PROD
#undef V1_ISZERO
#undef V1_SUP
#undef V1_NORMAL
#undef M1_INVERT
#undef MT1_TIMES_V1
#undef V2_LINCOMB
#undef V2_SET
#undef V2_COPY
#undef V2_SUBTRACT
#undef V2_ADD
#undef V2_ADD1
#undef V2_AVG2
#undef V2_AVG3
#undef V2_AVG4
#undef V2_SCALE
#undef V2_SCALEADD1
#undef V2_SCALESET
#undef V2_VECTOR_PRODUCT
#undef V2_COMPARE
#undef V2_ISEQUAL
#undef V2_EUKLIDNORM
#undef V2_EUKLIDNORM_OF_DIFF
#undef V2_CLEAR
#undef V2_SCALAR_PRODUCT
#undef V2_SCAL_PROD
#undef V2_ISZERO
#undef V2_SUP
#undef V2_NORMAL
#undef M2_TIMES_V2
#undef MM2_TIMES_V2
#undef MT2_TIMES_V2
#undef MD2_TIMES_V2
#undef M2_SCALE
#undef M2_ADD
#undef M2_COPY
#undef MM2_COPY
#undef M2_DET
#undef MM2_DET
#undef M2_LINCOMB
#undef M2_TIMES_M2
#undef M2_INVERT_STD
#undef M2_INVERT
#undef M2_MAXNORM
#undef V3_LINCOMB
#undef V3_SET
#undef V3_COPY
#undef V3_SUBTRACT
#undef V3_ADD
#undef V3_ADD1
#undef V3_AVG2
#undef V3_AVG3
#undef V3_AVG4
#undef V3_SCALE
#undef V3_SCALEADD1
#undef V3_SCALESET
#undef V3_VECTOR_PRODUCT
#undef V3_EUKLIDNORM
#undef V3_COMPARE
#undef V3_ISEQUAL
#undef V3_EUKLIDNORM_OF_DIFF
#undef V3_CLEAR
#undef V3_SCALAR_PRODUCT
#undef V3_SCAL_PROD
#undef V3_ISZERO
#undef V3_SUP
#undef M3_TIMES_V3
#undef MM3_TIMES_V3
#undef MT3_TIMES_V3
#undef MD3_TIMES_V3
#undef M3_SCALE
#undef M3_COPY
#undef MM3_COPY
#undef M3_DET
#undef MM3_DET
#undef M3_ADD
#undef M3_ADDMATRIX
#undef M3_LINCOMB
#undef M3_TIMES_M3
#undef M3_INVERT
#undef M4_TIMES_M4
#undef M4_TIMES_M4
#undef M4_COPY
#undef M4_CLEAR
#undef EX_MAT
#undef V_BDIM_LINCOMB
#undef V_BDIM_SET
#undef V_BDIM_COPY
#undef V_BDIM_SUBTRACT
#undef V_BDIM_ADD
#undef V_BDIM_ADD1
#undef V_BDIM_AVG2
#undef V_BDIM_AVG3
#undef V_BDIM_AVG4
#undef V_BDIM_SCALE
#undef V_BDIM_SCALEADD1
#undef V_BDIM_SCALESET
#undef V_BDIM_VECTOR_PRODUCT
#undef V_BDIM_COMPARE
#undef V_BDIM_ISEQUAL
#undef V_BDIM_EUKLIDNORM
#undef V_BDIM_EUKLIDNORM_OF_DIFF
#undef V_BDIM_CLEAR
#undef V_BDIM_SCALAR_PRODUCT
#undef V_BDIM_SCAL_PROD
#undef V_BDIM_ISZERO
#undef V_BDIM_SUP
#undef V_BDIM_Normalize
#undef M_BDIM_INVERT
#undef MT_TIMES_V_BDIM
#undef V_DIM_LINCOMB
#undef V_DIM_SET
#undef V_DIM_COPY
#undef V_DIM_SUBTRACT
#undef V_DIM_ADD
#undef V_DIM_ADD1
#undef V_DIM_AVG2
#undef V_DIM_AVG3
#undef V_DIM_AVG4
#undef V_DIM_SCALE
#undef V_DIM_SCALEADD1
#undef V_DIM_SCALESET
#undef V_DIM_VECTOR_PRODUCT
#undef V_DIM_COMPARE
#undef V_DIM_ISEQUAL
#undef V_DIM_EUKLIDNORM
#undef V_DIM_EUKLIDNORM_OF_DIFF
#undef V_DIM_CLEAR
#undef V_DIM_SCALAR_PRODUCT
#undef V_DIM_SCAL_PROD
#undef V_DIM_SP
#undef V_DIM_ISZERO
#undef V_DIM_SUP
#undef V_DIM_Normalize
#undef V_DIM_NORMAL
#undef M_TIMES_V_DIM
#undef MM_TIMES_V_DIM
#undef MT_TIMES_V_DIM
#undef MD_TIMES_V_DIM
#undef M_DIM_ADD
#undef M_DIM_COPY
#undef MM_DIM_COPY
#undef M_DIM_DET
#undef MM_DIM_DET
#undef M_DIM_SCALE
#undef M_DIM_INVERT
#undef V_BDIM_LINCOMB
#undef V_BDIM_SET
#undef V_BDIM_COPY
#undef V_BDIM_SUBTRACT
#undef V_BDIM_ADD
#undef V_BDIM_ADD1
#undef V_BDIM_AVG2
#undef V_BDIM_AVG3
#undef V_BDIM_AVG4
#undef V_BDIM_SCALE
#undef V_BDIM_SCALEADD1
#undef V_BDIM_SCALESET
#undef V_BDIM_VECTOR_PRODUCT
#undef V_BDIM_COMPARE
#undef V_BDIM_ISEQUAL
#undef V_BDIM_EUKLIDNORM
#undef V_BDIM_EUKLIDNORM_OF_DIFF
#undef V_BDIM_CLEAR
#undef V_BDIM_SCALAR_PRODUCT
#undef V_BDIM_SCAL_PROD
#undef V_BDIM_ISZERO
#undef V_BDIM_SUP
#undef V_BDIM_Normalize
#undef M_BDIM_INVERT
#undef MT_TIMES_V_BDIM
#undef V_DIM_LINCOMB
#undef V_DIM_SET
#undef V_DIM_COPY
#undef V_DIM_SUBTRACT
#undef V_DIM_ADD
#undef V_DIM_ADD1
#undef V_DIM_AVG2
#undef V_DIM_AVG3
#undef V_DIM_AVG4
#undef V_DIM_SCALE
#undef V_DIM_SCALEADD1
#undef V_DIM_SCALESET
#undef V_DIM_VECTOR_PRODUCT
#undef V_DIM_COMPARE
#undef V_DIM_ISEQUAL
#undef V_DIM_EUKLIDNORM
#undef V_DIM_EUKLIDNORM_OF_DIFF
#undef V_DIM_CLEAR
#undef V_DIM_SCALAR_PRODUCT
#undef V_DIM_SCAL_PROD
#undef V_DIM_SP
#undef V_DIM_ISZERO
#undef M_TIMES_V_DIM
#undef MM_TIMES_V_DIM
#undef MT_TIMES_V_DIM
#undef MD_TIMES_V_DIM
#undef M_DIM_ADD
#undef M_DIM_COPY
#undef MM_DIM_COPY
#undef M_DIM_DET
#undef MM_DIM_DET
#undef M_DIM_SCALE
#undef V_DIM_Normalize
#undef V_DIM_NORMAL
#undef M_DIM_INVERT
#undef V_DIM_SUP
#undef __ALGEBRA__
#undef GET_MATRIX
#undef EBUILDCON_SHIFT
#undef EBUILDCON_LEN
#undef EBUILDCON
#undef SETEBUILDCON
#undef VBUILDCON
#undef SETVBUILDCON
#undef __REFINE__
#undef NOTUSED
#undef NO_CENTER_NODE
#undef IDENT_ONLY_NEW
#undef __ANISOTROPIC__
#undef PATTERN_SHIFT
#undef PATTERN_LEN
#undef PATTERN
#undef SETPATTERN
#undef ADDPATTERN_SHIFT
#undef ADDPATTERN_LEN
#undef ADDPATTERN
#undef SETADDPATTERN
#undef REFINE_SHIFT
#undef REFINE_LEN
#undef REFINE
#undef SETREFINE
#undef MARK_SHIFT
#undef MARK_LEN
#undef MARK
#undef SETMARK
#undef COARSEN_SHIFT
#undef COARSEN_LEN
#undef COARSEN
#undef SETCOARSEN
#undef DECOUPLED_SHIFT
#undef DECOUPLED_LEN
#undef DECOUPLED
#undef SETDECOUPLED
#undef REFINECLASS_SHIFT
#undef REFINECLASS_LEN
#undef REFINECLASS
#undef SETREFINECLASS
#undef UPDATE_GREEN_SHIFT
#undef UPDATE_GREEN_LEN
#undef UPDATE_GREEN
#undef SETUPDATE_GREEN
#undef SIDEPATTERN_SHIFT
#undef SIDEPATTERN_LEN
#undef SIDEPATTERN
#undef SETSIDEPATTERN
#undef MARKCLASS_SHIFT
#undef MARKCLASS_LEN
#undef MARKCLASS
#undef SETMARKCLASS
#undef NEW_NIDENT_LEN
#undef NEW_NIDENT
#undef SETNEW_NIDENT
#undef NEW_EDIDENT_LEN
#undef NEW_EDIDENT
#undef SETNEW_EDIDENT
#undef RINFO_MAX
#undef REFINEINFO
#undef REFINESTEP
#undef SETREFINESTEP
#undef MARKCOUNT
#undef SETMARKCOUNT
#undef PREDNEW0
#undef SETPREDNEW0
#undef PREDNEW1
#undef SETPREDNEW1
#undef PREDNEW2
#undef SETPREDNEW2
#undef REAL
#undef SETREAL
#undef PREDMAX
#undef SETPREDMAX
#undef REFINE_ELEMENT_LIST
#undef REFINE_GRID_LIST
#undef REFINE_MULTIGRID_LIST
#undef __UGM__
#undef MAX_PAR_DIST
#undef PutFreeObject
#undef GetMemoryForObject
#undef GetMemoryForObject
#undef PutFreeObject
#undef GetMemoryForObject
#undef PutFreeObject
#undef FIRSTPART_OF_LIST
#undef LASTPART_OF_LIST
#undef HDRELEMENT
#undef HDRNODE
#undef HDRVERTEX
#undef HDRVECTOR
#undef HDR
#undef ELEMENTFMT
#undef NODEFMT
#undef VERTEXFMT
#undef VECTORFMT
#undef FORMAT
#undef COUNTELEMENT
#undef COUNTNODE
#undef COUNTVERTEX
#undef COUNTVECTOR
#undef PRIOCOUNTELEMENT
#undef PRIOCOUNTNODE
#undef PRIOCOUNTVERTEX
#undef PRIOCOUNTVECTOR
#undef UNLINK
#undef LINK
#undef LINKX
#undef INIT
#undef CHECK
#undef PRINT_LIST
